### ISSUE TITLE
3DS, Wii, and Switch ports don't play PINBALL.ogg if user is using Full Tilt Pinball assets [pull request? patch?]

### ISSUE THREAD

**Issue by signer-ink-beast** [MaikelChan/SpaceCadetPinball#11]
I have been enjoying your 3DS port of the game and play it using the Full Tilt Pinball assets, but I found it doesn't play the music, even when PINBALL.ogg is placed where the game expects it and it's the proper sample rate.

I looked at the code and found it is an easy fix in these three ports. In `SpaceCadetPinball/midi.cpp`, change line 74 from `track1 = load_track("TABA1");` to `track1 = load_track("PINBALL");`.

I can confirm the 3DS port plays PINBALL.ogg with that change. I can test the Wii port later. I don't have a Switch.

I have never sent a pull request before, and I don't know if I should do that or just attach a patch here since it is just one file and a trivial fix.

Edit: I also forgot to mention that these ports will expect them to be in the sound subfolder that Full Tilt has its sounds and music tracks stored in if you're using files from Full Tilt. For instance, for the 3DS port with Full Tilt files, the music needs to be in `sd:/3ds/SpaceCadetPinball/SOUND/PINBALL.ogg`.

**Comment by ghost** [comment]
I'm having trouble getting any audio to work at all, on my Old 3DS. I'm using the files from the Windows XP version. You only mentioned that the music isn't working for you, would you be so kind as to please tell me what your files look like/what directories you put them in?

**Comment by MaikelChan** [comment]
Sorry for the very delayed answer.

I didn't expect for Full Tilt to work, didn't try till now. Some elements don't fit the screen perfectly, but the important part, the board, looks nice.

Regarding the music, I would prefer to respect the Full Tilt audio file names, since there are multiple music files. The player could convert all the songs to OGG to better match the original game. So instead of changing code, it would be best to change the OGG file to TABA1.ogg.

I probably should add this info to the README.

@EndLordMC You should have PINBALL.ogg inside the SpaceCadetPinball folder, along with all the other files.

**Comment by MaikelChan** [comment]
I just updated the README with Full Tilt instructions.
