### ISSUE TITLE
crash on load (wii)

### ISSUE THREAD

**Issue by NyTR0S96** [MaikelChan/SpaceCadetPinball#4]
idk what I'm doing wrong. . . I have the assets in the data folder and its the origional xp pinball and not full tilt (allthough i think it would work either or) but no matter what I do when i go to load the program it instantly crashes and brings up a bunch of numbers and errors.

**Comment by MaikelChan** [comment]
I should add some error message printing on screen on common error situations. However, if you get that error screen, it probably is not because of missing assets. Do you run it on a NTSC or PAL Wii?

**Comment by NyTR0S96** [comment]
NTSC

**Comment by NyTR0S96** [comment]
[This](https://imgur.com/a/uthZ8sZ) is the error when i launch the program.

**Comment by MaikelChan** [comment]
Could you try this version and see if it crashes?

[SpaceCadetPinball.zip](https://github.com/MaikelChan/SpaceCadetPinball/files/7479826/SpaceCadetPinball.zip)

**Comment by NyTR0S96** [comment]
I will try it when I get home but I'm going to be home until tomorrow
**EDIT:** Same error.

**Comment by NyTR0S96** [comment]
is it a file structure issue?

**Comment by MaikelChan** [comment]
Not sure actually. In that new build, I changed some video output parameters and left them with default values. Incorrect values would cause a similar crashes to me. The values I used work fine in PAL, and since you have NTSC, I thought the values could be incompatible. But it doesn't seem to be the case.

Can you make another screenshot of the error in the new build?

From what I saw from your previous screenshot, is that it could be related to file access, but some of the data in the screenshot didn't make much sense to me. I've read that having corrupt files could cause a similar error, and reformatting the SD card and copying the files again could fix it.

But I cannot be certain right now.

**Comment by NyTR0S96** [comment]
![20211105_205611.jpg](https://user-images.githubusercontent.com/19482930/140597225-df8a9c59-810e-45a2-b29f-c129d3e4276f.jpg)

**Comment by NyTR0S96** [comment]
i'm not sure if anything changed in the errors but this is with your new .dol file

**Comment by MaikelChan** [comment]
Ok, this actually makes much more sense. The other one was weird for some reason.

Looks like your data files from the PC version are a bit different or something. Those would also break in the original PC decompilation and the other ports. You are triggering this assert located in `DatFile::Finalize()`:
`assertm(groupIndex < 0, "DatFile: pbmsg_ft is already in .dat");`

Since I only did the Wii and 3DS ports, I'm not all that familiar with all the variants that exist of this game and what is the reason your PINBALL.DAT is different. I'll transfer this issue to the PC decompilation repository. Its author could probably help you better in this case.

I'm sorry I cannot be of more help right now. For now, you could try to get the original assets from another place and see if there's more luck with those.

**Comment by MaikelChan** [comment]
Ok, this actually makes much more sense. The other one was weird for some reason.

It looks like you are missing pinball.exe and PINBALL2.MID (even if it has a MID extension, it's not a music file). Those would be required for the game to run, as they contain the font used in the game.

**Comment by NyTR0S96** [comment]
wait so i DO need the exe? thats wierd because i thought that wasn't needed.. . . wierd. also the .MID i thought sence it wouldn't play than i wouldn't need it so i excluded it. let me try it.

**Comment by NyTR0S96** [comment]
so it works however the music sounds slightly off pitch.

**Comment by MaikelChan** [comment]
I'm glad it's finally working. Regarding the music, maybe this is your issue? https://github.com/MaikelChan/SpaceCadetPinball/issues/5
