### ISSUE TITLE
game look too small even on a xl here recommendation.

### ISSUE THREAD

**Issue by ZombieConker** [MaikelChan/SpaceCadetPinball#8]
You should move highscore to bottom screen and leave the table all alone dead center otherwise i am distracted be the huge highscore next to the already small table so making it alone on the top  3d screen would help playing and the touch screen ball left should be merge with the highscore on the bottom touch screen ,otherwise it is a welcome addition to have this on a 3ds thanks again.

**Comment by MaikelChan** [comment]
I tried multiple layouts before deciding to stick with the current one. Having the score board at the bottom screen along with the logo and the ball count, requires having both elements very small due to the bottom screen being smaller. And text becomes unreadable at that point. So even if it's not ideal, the current setup makes everything readable. The main table would not be bigger by removing the score board from the top screen anyway.

However, I could make the score board a little bit smaller and move the main table more to the center.

**Comment by ZombieConker** [comment]
I know that i just think it would look more impressive in the middle alone can you add the option to swap them at least for those who want it differently thanks ,like in any way we want even bottom screen could possibly add touch control for tilt or even using the ds pen to play altogether but that another thing so it is up to you

**Comment by vaguerant** [comment]
@MaikelChan, I haven't actually tried your 3DS port yet, so I'm sorry if this is something you've already done, but it doesn't seem like it based on a quick look at the source. Have you considered supporting the 800px mode supported by all New 3DS model screens (including the New 2DS)? Obviously, the original game runs at twice the resolution of the "normal" 3DS setup of 400\*240, so you're losing a lot of detail in the scale down to 240 lines, but with `gfxSetWide` in libctru, you can run the 3DS top screen at 800\*240, with each pixel being half-width. That way, you'd only be losing half as much detail by scaling down, i.e. the game could run at native resolution on the horizontal axis, instead of half-resolution on both.
